export const ADMIN_STATS_REQUEST = 'ADMIN_STATS_REQUEST';
export const ADMIN_STATS_SUCCESS = 'ADMIN_STATS_SUCCESS';
export const ADMIN_STATS_FAIL = 'ADMIN_STATS_FAIL';

export const ADMIN_USER_BAN_REQUEST = 'ADMIN_USER_BAN_REQUEST';
export const ADMIN_USER_BAN_SUCCESS = 'ADMIN_USER_BAN_SUCCESS';
export const ADMIN_USER_BAN_FAIL = 'ADMIN_USER_BAN_FAIL';

export const ADMIN_ALL_ADOPTION_REQUEST_REQUEST =
  'ADMIN_ALL_ADOPTION_REQUEST_REQUEST';
export const ADMIN_ALL_ADOPTION_REQUEST_SUCCESS =
  'ADMIN_ALL_ADOPTION_REQUEST_SUCCESS';
export const ADMIN_ALL_ADOPTION_REQUEST_FAIL =
  'ADMIN_ALL_ADOPTION_REQUEST_FAIL';

export const ADMIN_ALL_MISSING_INFO_REQUEST = 'ADMIN_ALL_MISSING_INFO_REQUEST';
export const ADMIN_ALL_MISSING_INFO_SUCCESS = 'ADMIN_ALL_MISSING_INFO_SUCCESS';
export const ADMIN_ALL_MISSING_INFO_FAIL = 'ADMIN_ALL_MISSING_INFO_FAIL';
