export const ADOPTION_POST_REQUEST = 'ADOPTION_POST_REQUEST';
export const ADOPTION_POST_SUCCESS = 'ADOPTION_POST_SUCCESS';
export const ADOPTION_POST_FAIL = 'ADOPTION_POST_FAIL';

export const ADOPTION_POST_BY_ID_REQUEST = 'ADOPTION_POST_BY_ID_REQUEST';
export const ADOPTION_POST_BY_ID_SUCCESS = 'ADOPTION_POST_BY_ID_SUCCESS';
export const ADOPTION_POST_BY_ID_FAIL = 'ADOPTION_POST_BY_ID_FAIL';
