export const ADOPTION_POST_REQUEST = 'ADOPTION_POST_REQUEST';
export const ADOPTION_POST_SUCCESS = 'ADOPTION_POST_SUCCESS';
export const ADOPTION_POST_FAIL = 'ADOPTION_POST_FAIL';

export const ADOPTION_POST_BY_ID_REQUEST = 'ADOPTION_POST_BY_ID_REQUEST';
export const ADOPTION_POST_BY_ID_SUCCESS = 'ADOPTION_POST_BY_ID_SUCCESS';
export const ADOPTION_POST_BY_ID_FAIL = 'ADOPTION_POST_BY_ID_FAIL';

export const ADOPTION_POST_CREATE_REQUEST = 'ADOPTION_POST_CREATE_REQUEST';
export const ADOPTION_POST_CREATE_SUCCESS = 'ADOPTION_POST_CREATE_SUCCESS';
export const ADOPTION_POST_CREATE_FAIL = 'ADOPTION_POST_CREATE_FAIL';
export const ADOPTION_POST_CREATE_RESET = 'ADOPTION_POST_CREATE_RESET';

export const ADOPTION_POST_UPDATE_REQUEST = 'ADOPTION_POST_UPDATE_REQUEST';
export const ADOPTION_POST_UPDATE_SUCCESS = 'ADOPTION_POST_UPDATE_SUCCESS';
export const ADOPTION_POST_UPDATE_FAIL = 'ADOPTION_POST_UPDATE_FAIL';

export const ADOPTION_POSTS_BY_USERID_REQUEST =
  'ADOPTION_POSTS_BY_USERID_REQUEST';
export const ADOPTION_POSTS_BY_USERID_SUCCESS =
  'ADOPTION_POSTS_BY_USERID_SUCCESS';
export const ADOPTION_POSTS_BY_USERID_FAIL = 'ADOPTION_POSTS_BY_USERID_FAIL';

export const ADOPTION_REQUEST_REQUEST = 'ADOPTION_REQUEST_REQUEST';
export const ADOPTION_REQUEST_SUCCESS = 'ADOPTION_REQUEST_SUCCESS';
export const ADOPTION_REQUEST_FAIL = 'ADOPTION_REQUEST_FAIL';
export const ADOPTION_REQUEST_RESET = 'ADOPTION_REQUEST_RESET';

export const ADOPTION_POST_DELETE_REQUEST = 'ADOPTION_POST_DELETE_REQUEST';
export const ADOPTION_POST_DELETE_SUCCESS = 'ADOPTION_POST_DELETE_SUCCESS';
export const ADOPTION_POST_DELETE_FAIL = 'ADOPTION_POST_DELETE_FAIL';
export const ADOPTION_POST_DELETE_RESET = 'ADOPTION_POST_DELETE_RESET';
