export const ADOPTION_REQUEST_BY_ID_REQUEST = 'ADOPTION_REQUEST_BY_ID_REQUEST';
export const ADOPTION_REQUEST_BY_ID_SUCCESS = 'ADOPTION_REQUEST_BY_ID_SUCCESS';
export const ADOPTION_REQUEST_BY_ID_FAIL = 'ADOPTION_REQUEST_BY_ID_FAIL';

export const ADOPTION_REQUESTS_BY_USERID_REQUEST =
  'ADOPTION_REQUESTS_BY_USERID_REQUEST';
export const ADOPTION_REQUESTS_BY_USERID_SUCCESS =
  'ADOPTION_REQUESTS_BY_USERID_SUCCESS';
export const ADOPTION_REQUESTS_BY_USERID_FAIL =
  'ADOPTION_REQUESTS_BY_USERID_FAIL';

export const ADOPTION_REQUEST_APPROVE_REQUEST =
  'ADOPTION_REQUEST_APPROVE_REQUEST';
export const ADOPTION_REQUEST_APPROVE_SUCCESS =
  'ADOPTION_REQUEST_APPROVE_SUCCESS';
export const ADOPTION_REQUEST_APPROVE_FAIL = 'ADOPTION_REQUEST_APPROVE_FAIL';
export const ADOPTION_REQUEST_APPROVE_RESET = 'ADOPTION_REQUEST_APPROVE_RESET';
