export const DONATION_POST_CREATE_REQUEST = 'DONATION_POST_CREATE_REQUEST';
export const DONATION_POST_CREATE_SUCCESS = 'DONATION_POST_CREATE_SUCCESS';
export const DONATION_POST_CREATE_FAIL = 'DONATION_POST_CREATE_FAIL';
export const DONATION_POST_CREATE_RESET = 'DONATION_POST_CREATE_RESET';

export const DONATION_POSTS_REQUEST = 'DONATION_POSTS_REQUEST';
export const DONATION_POSTS_SUCCESS = 'DONATION_POSTS_SUCCESS';
export const DONATION_POSTS_FAIL = 'DONATION_POSTS_FAIL';

export const DONATION_POST_BY_ID_REQUEST = 'DONATION_POST_BY_ID_REQUEST';
export const DONATION_POST_BY_ID_SUCCESS = 'DONATION_POST_BY_ID_SUCCESS';
export const DONATION_POST_BY_ID_FAIL = 'DONATION_POST_BY_ID_FAIL';
