export const DONATION_GIVER_CREATE_REQUEST = 'DONATION_GIVER_CREATE_REQUEST';
export const DONATION_GIVER_CREATE_SUCCESS = 'DONATION_GIVER_CREATE_SUCCESS';
export const DONATION_GIVER_CREATE_FAIL = 'DONATION_GIVER_CREATE_FAIL';
export const DONATION_GIVER_CREATE_RESET = 'DONATION_GIVER_CREATE_RESET';
