export const DONATION_CREATE_REQUEST = 'DONATION_CREATE_REQUEST';
export const DONATION_CREATE_SUCCESS = 'DONATION_CREATE_SUCCESS';
export const DONATION_CREATE_FAIL = 'DONATION_CREATE_FAIL';
export const DONATION_CREATE_RESET = 'DONATION_CREATE_RESET';
