export const DONATION_CREATE_REQUEST = 'DONATION_CREATE_REQUEST';
export const DONATION_CREATE_SUCCESS = 'DONATION_CREATE_SUCCESS';
export const DONATION_CREATE_FAIL = 'DONATION_CREATE_FAIL';
export const DONATION_CREATE_RESET = 'DONATION_CREATE_RESET';

export const DONATION_BY_USERID_REQUEST = 'DONATION_BY_USERID_REQUEST';
export const DONATION_BY_USERID_SUCCESS = 'DONATION_BY_USERID_SUCCESS';
export const DONATION_BY_USERID_FAIL = 'DONATION_BY_USERID_FAIL';
export const DONATION_BY_USERID_RESET = 'DONATION_BY_USERID_RESET';
