export const MISSING_POST_REQUEST = 'MISSING_POST_REQUEST';
export const MISSING_POST_SUCCESS = 'MISSING_POST_SUCCESS';
export const MISSING_POST_FAIL = 'MISSING_POST_FAIL';

export const MISSING_POST_BY_ID_REQUEST = 'MISSING_POST_BY_ID_REQUEST';
export const MISSING_POST_BY_ID_SUCCESS = 'MISSING_POST_BY_ID_SUCCESS';
export const MISSING_POST_BY_ID_FAIL = 'MISSING_POST_BY_ID_FAIL';

export const MISSING_POSTS_BY_USERID_REQUEST =
  'MISSING_POSTS_BY_USERID_REQUEST';
export const MISSING_POSTS_BY_USERID_SUCCESS =
  'MISSING_POSTS_BY_USERID_SUCCESS';
export const MISSING_POSTS_BY_USERID_FAIL = 'MISSING_POSTS_BY_USERID_FAIL';
