export const MISSING_INFO_REQUEST = 'MISSING_INFO_REQUEST';
export const MISSING_INFO_SUCCESS = 'MISSING_INFO_SUCCESS';
export const MISSING_INFO_FAIL = 'MISSING_INFO_FAIL';

export const MISSING_INFO_BY_ID_REQUEST = 'MISSING_INFO_BY_ID_REQUEST';
export const MISSING_INFO_BY_ID_SUCCESS = 'MISSING_INFO_BY_ID_SUCCESS';
export const MISSING_INFO_BY_ID_FAIL = 'MISSING_INFO_BY_ID_FAIL';

export const MISSING_INFO_APPROVE_REQUEST = 'MISSING_INFO_APPROVE_REQUEST';
export const MISSING_INFO_APPROVE_SUCCESS = 'MISSING_INFO_APPROVE_SUCCESS';
export const MISSING_INFO_APPROVE_FAIL = 'MISSING_INFO_APPROVE_FAIL';
export const MISSING_INFO_APPROVE_RESET = 'MISSING_INFO_APPROVE_RESET';
